name: QA Automation Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright
        run: python -m playwright install --with-deps

      - name: Run tests
        run: pytest tests -s -vv --alluredir=allure-results

      - name: Generate Metrics
        run: python scripts/metrics_collector.py

      - name: Generate Charts
        run: python scripts/generate_charts.py

      - name: Upload Metrics
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: metrics