name: QA Automation Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write


jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug structure (IMPORTANT)
        run: ls -R

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r project_1_ui_ecommerce/requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run tests
        run: pytest project_1_ui_ecommerce/tests -s -vv --maxfail=1 --alluredir=allure-results

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Metrics
        run: python project_1_ui_ecommerce/scripts/metrics_collector.py

      - name: Generate Charts
        run: python project_1_ui_ecommerce/scripts/generate_charts.py

      - name: Upload Metrics
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: project_1_ui_ecommerce/metrics


  report:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download results
        uses: actions/download-artifact@v4
        with:
          name: allure-results

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g allure-commandline

      - name: Generate report
        run: allure generate allure-results -o allure-report --clean

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report


  deploy:
    needs: report
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4