name: Deploy Allure Report

on:
  workflow_run:
    workflows: ["CI - Docker UI Tests"]
    types:
      - completed

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results

      - name: Install Node
        run: npm install -g allure-commandline

      - name: Generate report
        run: allure generate allure-results -o allure-report --clean

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  publish:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4